CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS COMPANIES(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    NUMBER_DOCUMENT NOT NULL,
    DOCUMENT_TYPE NOT NULL,
    OWNER_ID NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PERSONS_ID PRIMARY KEY(ID)
);
