CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS COMPANIES(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    OWNER_ID NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    COMPANY NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    DUE_DATE DATE NOT NULL,
    AMOUNT DECIMAL NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    AMOUNT_PAYMENT DOUBLE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PERSONS_ID PRIMARY KEY(ID)
);
