CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS PERSONS(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    NAME VARCHAR(150) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PERSONS_ID PRIMARY KEY(ID)
);
